require("aleksandr.nvim_settings")
require("aleksandr.lazy")
require("aleksandr.telescope")
require("aleksandr.treesitter")
require("aleksandr.ibl")
require("aleksandr.yazi")
require("aleksandr.dracula")
-- require("aleksandr.rose_pine")
require("aleksandr.avante")
require("aleksandr.zen_mode")
require("aleksandr.nvim_tree")
require("aleksandr.lsp")
require("aleksandr.nvm_cmp")
require("aleksandr.git_signs")
-- require("aleksandr.supermaven")
require("aleksandr.auto_pairs")
require("aleksandr.lualine")
require("aleksandr.auto_tag")
require("aleksandr.nvim_comment")
-- require("aleksandr.coc")
require("aleksandr.reload")
--require("aleksandr.which_key")
